### ISSUE TITLE
Does not appear on the list of modules

### ISSUE THREAD

**Issue by caecos** [philippesalembier/SckitamVCV#1]
Your sources compile fine in MSYS on Windows but once the folder place in the plugins folder of VCV, yours modules does not appear???

**Comment by caecos** [comment]
Here's the complete compile file:

$ RACK_DIR=C:/msys64/Rack-SDK make dist
g++  -std=c++11 -Wsuggest-override   -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/widgets.cpp.o src/widgets.cpp
g++  -std=c++11 -Wsuggest-override   -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/plugin.cpp.o src/plugin.cpp
g++  -std=c++11 -Wsuggest-override   -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/PolygonalVCO.cpp.o src/PolygonalVCO.cpp
g++  -std=c++11 -Wsuggest-override   -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/2DRotation.cpp.o src/2DRotation.cpp
g++  -std=c++11 -Wsuggest-override   -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/2DAffine.cpp.o src/2DAffine.cpp
g++  -std=c++11 -Wsuggest-override   -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/MarkovSeq.cpp.o src/MarkovSeq.cpp
src/MarkovSeq.cpp: In member function 'virtual void MarkovSeq::process(const rack::engine::Module::ProcessArgs&)':
src/MarkovSeq.cpp:256:9: warning: variable 'G0' set but not used [-Wunused-but-set-variable]
  256 |   float G0 = 0;
      |         ^~
g++ -o plugin.dll build/src/widgets.cpp.o build/src/plugin.cpp.o build/src/PolygonalVCO.cpp.o build/src/2DRotation.cpp.o build/src/2DAffine.cpp.o build/src/MarkovSeq.cpp.o  -shared -LC:/msys64/Rack-SDK -lRack
rm -rf dist
mkdir -p dist/"Sckitam"
cp plugin.dll dist/"Sckitam"/
strip -s dist/"Sckitam"/plugin.dll
cp -r --parents res  plugin.json dist/"Sckitam"/
cd dist && zip -q -9 -r "Sckitam"-"1.0.0"-win.zip "Sckitam"

**Comment by philippesalembier** [comment]
I think that there was an issue in the json file. I have updated it. Could you try now.

**Comment by caecos** [comment]
Great, it works now, many thanks for your quick reply...regards.
